### ISSUE TITLE
Attach SOMDEV1 / DEV2 to Qumulo

### ISSUE THREAD

**Issue by nmagee** [databio/LOLAweb#42]
Reach out to RCI and discuss options around mounting specific Qumulo shares to DEV1/DEV2. This will help us consolidate pools of reference / universe data.

**Comment by nmagee** [comment]
@nsheff Alden's reply to this request was "I can do this easy". ;)

**Comment by nsheff** [comment]
@nmagee Following up on this -- is this possible yet?

**Comment by nsheff** [comment]
Hi @nmagee, when you get a chance, can we follow up on this? What's the ETA? If beyond a week or so we should come up with an alternative solution I think.

**Comment by nmagee** [comment]
Sorry I didn't see this while I was away. Working on a proper/faster mount path, but for now this is mounted as read-only here on both nodes:

```
/mnt/q/shefflab
```

**Comment by nsheff** [comment]
I can see that; where is the corresponding mount on rivanna?

**Comment by nsheff** [comment]
nevermind I found it.

**Comment by nsheff** [comment]
at what external URL can I see the files in that folder?

**Comment by nsheff** [comment]
I've changed LOLA around to use environment variables and point to the qumulo mount (see #50)

With this commit, I'm trying to update the docker swarm so that the mounts are now correctly pointing to the new mounts, instead of to local subfolders inside the app dir.

https://github.com/databio/LOLAweb/commit/e936848e29e16360b2d046228ab95ea48e04ed61

@vpnagraj and @nmagee am I doing this correctly?

The new config works for me locally on my computer as long as I have those docker mounts correct.

**Comment by nsheff** [comment]
How do I tell the swarm to re-create the containers with the new mount points?

**Comment by nsheff** [comment]
actually, those new mount points will only work with dev containers... so this gets tricky. can you only update dev containers?

**Comment by vpnagraj** [comment]
@nsheff i'll let @nmagee speak to the swarm config ...

but for the changes in c2ec8d1 i can confirm i was able to get things set up and running locally (with `runApp()` outside of docker)

**Comment by nsheff** [comment]
It seems that I somehow updated the production containers, because they're now showing the new code... I am not sure what I did.

This also means they are not working anymore.

**Comment by nsheff** [comment]
actually this has me quite confused... I did not update the master Dockerfile. I thought that was the way to update the production containers. But the production containers are currently running the code on the dev branch of LOLAweb. It does not seem like this should happen, so something went wrong either in practice, or in the way I understand things.

**Comment by vpnagraj** [comment]
weird ... i don't think this has been an issue until today ??

@nmagee is this a typo?

https://github.com/databio/LOLAweb/blob/c1fc5d8a987de5e7d0f216a437f701c52c495486/docker/Dockerfile#L11

shouldn't have the `-b dev` flag, right?

my guess is that we hadn't seen this (even with recent commits to dev) since the container hadn't actually been rebuilt until @nsheff did the PR and reverted it today

**Comment by vpnagraj** [comment]
ok yeah that was definitely a typo ... bb34fec fixed things so that the production container *is* pulling from the master branch for code (rather than dev)

**Comment by nmagee** [comment]
Sorry guys, I was away all weekend and missed these. I'm going to update the swarm today between datacenter work. I'll keep you posted.

**Comment by nsheff** [comment]
that's working now, thanks.

**Comment by vpnagraj** [comment]
this is change was included in v1.2 release
