### ISSUE TITLE
dockerfile duplication

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#46]
Right now we have a different dockerfile for each branch (master, staging, dev). this caused me some confusion; is this the way we want it?

Shouldn't there be only a single docker file, and then the *branch* it's on dictates which container it's building?

**Comment by nmagee** [comment]
@nsheff yeah, with branches and builds of Dockerfiles there are basically two ways to go:

1. Create separate paths and multiple Dockerfiles, each specific to a git branch (the way we have it now); or
2. Use git attributes to prevent any merges of the Dockerfiles, so that each one remains unique for its particular branch.

I'd be fine with shifting over to the latter method; for whatever reason the former is more common in the Docker world.

**Comment by nsheff** [comment]
Well, I guess I like the former better than the latter. Still, it feels strange.
