### ISSUE TITLE
staging and dev

### ISSUE THREAD

**Issue by nsheff** [databio/LOLAweb#8]
@nmagee and @vpnagraj 

When we last talked, we thought about having master and dev branches with separate docker deploys. I now think your staging comment makes more sense; so we have dev for development, staging pushes that into a test docker environment, and then master is the real deploy.

that makes a lot of sense to me now, even for this.

**Comment by nmagee** [comment]
So @vpnagraj has done all the work of getting branches, and their respective Dockerfiles, all sorted out. I researched Traefik's options for mapping to prod / staging / dev using URL paths, but it appears that is not possible after all.

I have automated builds running correctly, but for the moment had to set those up in the SOMRC organization. Docker Hub and Docker Cloud aren't giving me access to Databio still (despite getting email from them confirming Docker Cloud access). But we can sort that out Wednesday, no prob.

My suggestion, with the three branches, is to run them through different hostnames after all. Traefik can run all of these in the same stack, mapping specific hostnames to specific sets of containers:

http://lolaweb.databio.org/
http://staging.lolaweb.databio.org/
http://dev.lolaweb.databio.org/ 

or

http://lolaweb.databio.org/
http://lolaweb-staging.databio.org/
http://lolaweb-dev.databio.org/

What do you think? For a proof of concept I set up http://dev.lolaweb.uvasomrc.io/ last night, which takes you to a single nginx container, within our stack.

**Comment by nsheff** [comment]
Ok,  interesting. I haven't had time to dig into traefik docs yet, but are you sure about this? By my cursory reading it seems to indicate that `domain.com/web` is mappable to a different microservice:

https://docs.traefik.io/basics/
https://github.com/containous/traefik/issues/73

**Comment by nmagee** [comment]
I'm still researching the idea of mapping containers to paths within the same site. Stay tuned.

In the meantime, I have made good progress on plumbing branches, images, and syncing behind the scenes:

1. We want to do our Docker builds in Travis-CI, not in Docker Hub or Cloud. Travis takes about 1/3 the time, comparatively (7-9mins) for the build, then pushes the respective image:tag up to Docker Hub.
2. Travis also allows me to more easily send a message to the server in order to have new images automatically injected into the various swarms. 
3. Nathan, there are some funky permissions issues going on with my access to Databio's organization in Docker -- it won't let me do much right now. In the meantime I'm just building images into the somrc organization in Docker. But we will get that figured out by Wednesday.
4. For reference, here is a mapping of branches, their respective container images, and their current URLs (for now). URLs could change depending on whether we can map subdirs to containers:

GitHub Branch | Docker Image | URL
------------ | ------------- | -------------
master | somrc/lolaweb:latest | http://lolaweb.databio.org/
staging | somrc/lolaweb:staging | http://staging.lolaweb.uvasomrc.io/
dev | somrc/lolaweb:dev | http://dev.lolaweb.uvasomrc.io/

5. [BY END OF BUSINESS TODAY] When you push code to GitHub, expect that the appropriate container will get built and injected into the Docker Stack within 8-11 minutes, give or take. I'll add some Travis badges later to indicate build status.

**Comment by nsheff** [comment]
Ok that sounds good. you are an owner of the databio org so you should have complete permission to do whatever you want there on dockerhub or docker cloud. I can't do anything you can't.

**Comment by nmagee** [comment]
Oh I totally believe you! I even got the notification emails from them saying as much.

**Comment by nmagee** [comment]
I've just watched Nathan's last two pushes build the container, push it up, and the server upgraded the container properly. So that's a good confirmation of the pipeline working smoothly.

**Comment by nmagee** [comment]
Also, it's good practice to give a bit of delay between rolling updates on a Docker swarm. So the back-end script on the server has a 10s wait between switching out containers.

    docker service update --update-delay 10s --image $CONTAINER service_name;

The `docker service update` command is great because it updates an existing service with no loss in the service, and it automatically pulls the new image down. (This is why you'll see the [Docker Hub pull counts](https://hub.docker.com/u/databio/dashboard/) already climbing.)

**Comment by nsheff** [comment]
I was watching, too. It worked great.  a few minutes later I refreshed the dev URL and saw my change. nice!

**Comment by nmagee** [comment]
Another random maintenance script: A weekly pruning of all "dangling" images no longer needed in the stack. They can add up over time.

I just added you both to this private repo for server-side things:
https://github.com/uvasomrc/lolaweb-backend

**Comment by nsheff** [comment]
Hey @nmagee -- can you add these as dev/staging urls

http://staging.lolaweb.databio.org/
http://dev.lolaweb.databio.org/

it's just easier to type `dev` on the front of the real url than switching to the uvasomrc.io domain.

**Comment by nmagee** [comment]
@nsheff -- yeah, I sure can. I meant to ask you about that Wednesday. Adding those domains right now.

I was teaching yesterday afternoon and ran out of time to touch the manuscript, so I'm doing that this morning. Look for a push or three before lunch.

**Comment by nmagee** [comment]
Done

**Comment by nsheff** [comment]
got it, that works now. probably makes sense to just make `lolaweb.databio.org` behave the same way as `lolaweb.uvasomrc.io` in every sense.

**Comment by nmagee** [comment]
@nsheff these are all mapped now, and tested. And made extra sure the main URL is alive and well...

[lolaweb.databio.org](http://lolaweb.databio.org)
[lolaweb.uvasomrc.io](http://lolaweb.uvasomrc.io)
[staging.lolaweb.databio.org](http://staging.lolaweb.databio.org)
[staging.lolaweb.uvasomrc.io](http://staging.lolaweb.uvasomrc.io)
[dev.lolaweb.databio.org](http://dev.lolaweb.databio.org)
[dev.lolaweb.uvasomrc.io](http://dev.lolaweb.uvasomrc.io)

I also just updated the Docker/Swarm documentation in master (for the reviewers) and in dev (for changes to carry forward henceforth). I still had references to old container image names, and added to the volumes mounted at runtime.

**Comment by nsheff** [comment]
hey, that means a user can have 6 simultaneous sessions, hehe.
